name: "panoramicovphc-sshwifty"

x-common-props: &common-props
  restart: "unless-stopped"
  dns:
    - "1.1.1.1"
    - "4.4.4.4"
  environment:
    PUID: "1000"
    PGID: "1000"
    TZ: "America/Sao_Paulo"
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/var/run/docker.sock:/var/run/docker.sock:ro"

services:

  sshwifty-srv:
    <<: *common-props
    image: "niruix/sshwifty:0.3.11-beta-release"
    container_name: "sshwifty-srv"
    hostname: "sshwifty-srv"
    environment:
      DEBUG: 1
    network_mode: "host"
    ports:
      - "8182:8182"

  sshwifty-vpc:
    <<: *common-props
    image: "cloudflare/cloudflared:latest"
    container_name: "sshwifty-vpc"
    hostname: "sshwifty-vpc"
    command: |
      tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    network_mode: "host"
